"""message

Revision ID: 253e400bd7f6
Revises: ff32de0f90f5
Create Date: 2023-09-14 11:47:54.387994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253e400bd7f6'
down_revision = 'ff32de0f90f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('media_path', sa.Text(), nullable=True))
    op.drop_column('events', 'picture_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('picture_path', sa.TEXT(), nullable=True))
    op.drop_column('events', 'media_path')
    # ### end Alembic commands ###
