"""message

Revision ID: 60f8a685b20e
Revises: 6d5078f2f1be
Create Date: 2023-09-12 15:45:24.664075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f8a685b20e'
down_revision = '6d5078f2f1be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthday', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
