"""message

Revision ID: b33fb1a42934
Revises: dc3e91bd347b
Create Date: 2023-09-12 16:46:50.873013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33fb1a42934'
down_revision = 'dc3e91bd347b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
