"""message

Revision ID: f49bf33c2a12
Revises: 9b440b32b799
Create Date: 2023-09-14 10:52:45.755742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49bf33c2a12'
down_revision = '9b440b32b799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('day', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'day')
    # ### end Alembic commands ###
