"""message

Revision ID: ff32de0f90f5
Revises: f49bf33c2a12
Create Date: 2023-09-14 11:15:56.982660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff32de0f90f5'
down_revision = 'f49bf33c2a12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
